# Import historique des livret PEE STEF (CSV) et CiC (Excel)

In [61]:
import pandas as pd
from sqlalchemy import create_engine
import config
from datetime import datetime

# 1. Connection à la DB
url = f"postgresql://{config.db_params['user']}:{config.db_params['password']}@{config.db_params['host']}:{config.db_params['port']}/{config.db_params['database']}"
engine = create_engine(url)

print("\nConnexion établie !")

Connexion établie !

### STEF

In [62]:
file = r"E:\Data\Tristan\Téléchargements\HistoriqueValeurPart_26_01_2021_26_01_2026.csv"

df_stef = pd.read_csv(
    file, 
    sep=';', 
    header=0,                                     # On ignore la ligne de titres d'origine
    names=['cot_date_prix', 'cot_prix_unitaire'], # On impose NOS noms de colonnes SQL
    usecols=[0, 1],
    parse_dates=['cot_date_prix'], 
    dayfirst=True)

df_stef['pdt_id'] = 3

df_stef

     cot_date_prix  cot_prix_unitaire  pdt_id
0       2021-01-26             49.180       3
1       2021-01-27             49.180       3
2       2021-01-28             48.999       3
3       2021-01-29             48.636       3
4       2021-02-01             48.636       3
...            ...                ...     ...
1246    2026-01-16             93.237       3
1247    2026-01-19             91.745       3
1248    2026-01-20             90.659       3
1249    2026-01-21             91.746       3
1250    2026-01-22             92.697       3

[1251 rows x 3 columns]

In [63]:
df_stef.to_sql('cotation_cot', engine, if_exists='append', index=False)
print("STEF importé")

STEF importé

### CiC

#### Livret Stratégie

In [64]:
start = '2022-01-01'

file = r"E:\Data\Tristan\Téléchargements\Historique Cours Strategie.xlsx"

df_cic_strat = pd.read_excel(
    file, 
    skiprows=6,                                   # On exclue des lignes au debut du fichier
    skipfooter=1,                                 # On exclue des lignes à la fin du fichier
    names=['cot_date_prix', 'cot_prix_unitaire'], # On impose NOS noms de colonnes SQL
    usecols=[0, 1],
    parse_dates=['cot_date_prix'],
    date_format="%d/%m/%Y")

df_cic_strat['pdt_id'] = 6
df_cic_strat = df_cic_strat[df_cic_strat['cot_date_prix'] >= start]

df_cic_strat

     cot_date_prix  cot_prix_unitaire  pdt_id
0       2026-01-22            16.4995       6
1       2026-01-21            16.2239       6
2       2026-01-20            16.2544       6
3       2026-01-19            16.2932       6
4       2026-01-16            16.5826       6
...            ...                ...     ...
1009    2022-01-07            24.3932       6
1010    2022-01-06            25.0709       6
1011    2022-01-05            25.4225       6
1012    2022-01-04            25.3567       6
1013    2022-01-03            25.7212       6

[1014 rows x 3 columns]

In [65]:
df_cic_strat.to_sql('cotation_cot', engine, if_exists='append', index=False)
print("CiC Strat importé")

CiC Strat importé

#### Livret Obligation

In [66]:
start = '2020-01-01'

file = r"E:\Data\Tristan\Téléchargements\Historique Cours Obligation.xlsx"

df_cic_obli = pd.read_excel(
    file, 
    skiprows=6,                                   # On exclue des lignes au debut du fichier
    skipfooter=1,                                 # On exclue des lignes à la fin du fichier
    names=['cot_date_prix', 'cot_prix_unitaire'], # On impose NOS noms de colonnes SQL
    usecols=[0, 1],
    parse_dates=['cot_date_prix'],
    date_format="%d/%m/%Y")

df_cic_obli['pdt_id'] = 4
df_cic_obli = df_cic_obli[df_cic_obli['cot_date_prix'] >= start]

df_cic_obli

     cot_date_prix  cot_prix_unitaire  pdt_id
0       2026-01-22             3.6630       4
1       2026-01-21             3.6628       4
2       2026-01-20             3.6652       4
3       2026-01-19             3.6661       4
4       2026-01-16             3.6645       4
...            ...                ...     ...
1514    2020-01-08             3.7777       4
1515    2020-01-07             3.7811       4
1516    2020-01-06             3.7817       4
1517    2020-01-03             3.7816       4
1518    2020-01-02             3.7771       4

[1519 rows x 3 columns]

In [67]:
df_cic_obli.to_sql('cotation_cot', engine, if_exists='append', index=False)
print("CiC Obli importé")

CiC Obli importé

#### Livret Equilibre

In [68]:
start = '2022-01-01'

file = r"E:\Data\Tristan\Téléchargements\Historique Cours Equilibre.xlsx"

df_cic_equi = pd.read_excel(
    file, 
    skiprows=6,                                   # On exclue des lignes au debut du fichier
    skipfooter=1,                                 # On exclue des lignes à la fin du fichier
    names=['cot_date_prix', 'cot_prix_unitaire'], # On impose NOS noms de colonnes SQL
    usecols=[0, 1],
    parse_dates=['cot_date_prix'],
    date_format="%d/%m/%Y")

df_cic_equi['pdt_id'] = 5
df_cic_equi = df_cic_equi[df_cic_equi['cot_date_prix'] >= start]

df_cic_equi

     cot_date_prix  cot_prix_unitaire  pdt_id
0       2026-01-22            16.2544       5
1       2026-01-21            16.1582       5
2       2026-01-20            16.1906       5
3       2026-01-19            16.2495       5
4       2026-01-16            16.3684       5
...            ...                ...     ...
1009    2022-01-07            14.2624       5
1010    2022-01-06            14.2909       5
1011    2022-01-05            14.4133       5
1012    2022-01-04            14.3958       5
1013    2022-01-03            14.3197       5

[1014 rows x 3 columns]

In [69]:
df_cic_equi.to_sql('cotation_cot', engine, if_exists='append', index=False)
print("CiC Equi importé")

CiC Equi importé

#### Livret Monétaire

In [73]:
start = '2019-01-01'
end = '2022-12-31'

file = r"E:\Data\Tristan\Téléchargements\Historique Cours Monetaire.xlsx"

df_cic_monet = pd.read_excel(
    file, 
    skiprows=6,                                   # On exclue des lignes au debut du fichier
    skipfooter=1,                                 # On exclue des lignes à la fin du fichier
    names=['cot_date_prix', 'cot_prix_unitaire'], # On impose NOS noms de colonnes SQL
    usecols=[0, 1],
    parse_dates=['cot_date_prix'],
    date_format="%d/%m/%Y")

df_cic_monet['pdt_id'] = 9
df_cic_monet = df_cic_monet[df_cic_monet['cot_date_prix'].between(start, end)]

df_cic_monet

     cot_date_prix  cot_prix_unitaire  pdt_id
764     2022-12-30             4.0261       9
765     2022-12-29             4.0255       9
766     2022-12-28             4.0254       9
767     2022-12-27             4.0252       9
768     2022-12-23             4.0250       9
...            ...                ...     ...
1764    2019-01-08             4.1149       9
1765    2019-01-07             4.1150       9
1766    2019-01-04             4.1150       9
1767    2019-01-03             4.1153       9
1768    2019-01-02             4.1153       9

[1005 rows x 3 columns]

In [71]:
df_cic_monet.to_sql('cotation_cot', engine, if_exists='append', index=False)
print("CiC Monet importé")

CiC Monet importé